version: '3'
services:

  # Backend
  snapp-test-app:
    container_name: snapp-test-app
    build:
      context: ../../
      dockerfile: .etc/docker/Dockerfile
      args:
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
    networks:
      - snapp-test-net

  # Nginx
  snapp-test-nginx:
    container_name: snapp-test-nginx
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt/certificate:/usr/share/nginx/certificate
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on: 
      - snapp-test-app
    networks:
      - snapp-test-net
  
  # Mysql  
  snapp-test-mysql:
    container_name: snapp-test-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33065:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - snapp-test-net
      
  # Mongo
  snapp-test-mongo:
    container_name: snapp-test-mongo
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - snapp-test-net
      
  # Rabbit
  snapp-test-rabbit:
    image: rabbitmq:3-management-alpine
    container_name: snapp-test-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbit/data:/var/lib/rabbitmq/
        - ./rabbit/log:/var/log/rabbitmq
    networks:
        - snapp-test-net

networks:
  snapp-test-net:
    driver: bridge